### ISSUE TITLE
**Feature Request** - Hide Tray Icon, Favorites Paths

### ISSUE THREAD

**Issue by samschultzponsys** [ThioJoe/AHK-Scripts#14]
Two things that would take this tool to the next level would be:

1. Allow me to hide the tray icon
2. Allow adding some predefined paths when using the tool, e.g. middle mouse pops up what I have open in explorer as well as has some other paths I have defined, would be awesome if unlimited but having a limit would still be amazing.

Thanks again for your awesome videos, I am glad to see the things you find and love seeing you progress in your skills!

**Comment by Banaanae** [comment]
Working on no. 1

**Comment by ThioJoe** [comment]
Version 1.2.0 now has the ability to add a custom favorites list and a conditional favorites feature.

**Comment by ThioJoe** [comment]
Gonna close this since I don't intend to add an option to hide the tray icon. If you want  you can simply add this line anywhere in the script to do so:

```
#NoTrayIcon
```

More info here: https://www.autohotkey.com/docs/v2/lib/_NoTrayIcon.htm

**Comment by ThioJoe** [comment]
Copying my comment from #17:

I added a setting in 1.2.5 but you'll need to just change it in the settings file directly by setting the line:

hideTrayIcon=1
Since it won't be your the existing settings file version, you can copy and add the line yourself, or if you open the settings GUI and hit 'save' it should just add the line to the settings file automatically with the default 0 value which you can then change.
